---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipam-controller-manager
  namespace: metal3-ipam-system
spec:
  template:
    spec:
      tolerations:
      # TODO (fmuyassarov): remove node-role.kubernetes.io/master
      # taint before moving to k8s v1.24
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
        - key: CriticalAddonsOnly
          operator: Exists
