apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      controller-tools.k8s.io: "1.0"
  template:
    metadata:
      labels:
        control-plane: controller-manager
        controller-tools.k8s.io: "1.0"
    spec:
      containers:
      - command:
        - /manager
        args:
        - "--webhook-port=9443"
        - "--diagnostics-address=${IPAM_DIAGNOSTICS_ADDRESS:=:8443}"
        - "--insecure-diagnostics=${IPAM_INSECURE_DIAGNOSTICS:=false}"
        - "--tls-min-version=${TLS_MIN_VERSION:=VersionTLS13}"
        image: controller:latest
        imagePullPolicy: IfNotPresent
        name: manager
        ports:
        - containerPort: 9440
          name: healthz
          protocol: TCP
        - containerPort: 8443
          name: metrics
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: healthz
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthz
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          runAsUser: 65532
          runAsGroup: 65532
        terminationMessagePolicy: FallbackToLogsOnError
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: manager
      tolerations:
      # TODO (fmuyassarov): remove node-role.kubernetes.io/master
      # taint before moving to k8s v1.24
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
