name: golangci-lint

on:
  pull_request:
    types: [ opened, edited, synchronize, reopened ]

permissions: {}

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        working-directory:
        - ""
        - api
        - hack/tools/release
        include:
        - working-directory: hack/tools/release
          additional-args: --build-tags=tools --modules-download-mode=readonly

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Calculate go version
      id: vars
      run: echo "go_version=$(make go-version)" >> $GITHUB_OUTPUT
    - name: Set up Go
      uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
      with:
        go-version: ${{ steps.vars.outputs.go_version }}
    - name: golangci-lint-${{matrix.working-directory}}
      uses: golangci/golangci-lint-action@55c2c1448f86e01eaae002a5a3a9624417608d84 # v6.5.2
      with:
        version: v1.64.7
        working-directory: ${{matrix.working-directory}}
        args: --timeout=10m ${{matrix.additional-args}}
