name: Check Markdown links

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]
    paths:
    - '**.md'

permissions: {}

jobs:
  markdown-link-check:
    name: Broken Links
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: gaurav-nelson/github-action-markdown-link-check@5c5dfc0ac2e225883c0e5f03a85311ec2830d368 # v1
      with:
        use-quiet-mode: 'yes'
        config-file: .markdownlinkcheck.json
